name: Kontrola Python pluginu

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Klon repozitáře
        uses: actions/checkout@v3

      - name: Nastavení Pythonu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalace flake8
        run: pip install flake8

      - name: Spuštění kontroly flake8
        run: flake8 .
